greenbay/config_test.go, greenbay/output_options_test.go, greenbay/output_producer_test.go, sthree/bucket_test.go, sthree/sync_from_test.go, sthree/sync_to_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-611
=> MAKE-611: fix compile after revendoring go.uuid

evergreen.yaml
JIRA: https://jira.mongodb.org/browse/MAKE-725
=> MAKE-725: make an S3 copy including GOOS and GOARCH

repobuilder/job.go
=> MAKE-793: increase repobuilder timeout

glide.lock, vendor/github.com/mongodb/jasper/cli/service_rest.go, vendor/github.com/mongodb/jasper/cli/service_rpc.go
JIRA: https://jira.mongodb.org/browse/MAKE-804
=> MAKE-804: change Jasper default ports to avoid conflicts with Evergreen ports

glide.lock, vendor/github.com/mongodb/jasper/cli/service.go, vendor/github.com/mongodb/jasper/cli/utils.go, vendor/github.com/mongodb/jasper/manager_self_clearing.go, vendor/github.com/mongodb/jasper/process_basic.go
JIRA: https://jira.mongodb.org/browse/MAKE-805
=> MAKE-805: revendor Jasper

operations/splunk.go
JIRA: https://jira.mongodb.org/browse/MAKE-894
=> MAKE-894: splunk command panics if setup fails

barquesubmit/client.go
JIRA: https://jira.mongodb.org/browse/MAKE-1167
=> MAKE-1167: fix barque URL builder

barquesubmit/client.go
JIRA: https://jira.mongodb.org/browse/MAKE-1172
=> MAKE-1172: POST to barque login instead of GET

barquesubmit/client.go
JIRA: https://jira.mongodb.org/browse/MAKE-1163
=> MAKE-1163: fix repobuilder check route

repobuilder/deb.go, timber_conf.yaml
Also remove extraneous timber conf file.
=> MAKE-1163: show stdout and stderr logs from deb job

.golangci.yml, cmd/run-linter/run-linter.go, greenbay/check/container.go, greenbay/interface.go, makefile, operations/buildlogger.go, operations/ftdc.go, operations/splunk.go, repobuilder/job.go
JIRA: https://jira.mongodb.org/browse/MAKE-1149
=> MAKE-1149: use golangci-lint

repobuilder/job.go
JIRA: https://jira.mongodb.org/browse/MAKE-1188
=> MAKE-1188: increase repobuilder timeout

operations/flag.go, operations/revendor.go
JIRA: https://jira.mongodb.org/browse/EVG-12452
=> EVG-12452: add short flags for revendor command

cmd/run-linter/run-linter.go, evergreen.yaml, greenbay/check/file_exists_test.go, greenbay/check/file_group_exists_test.go, makefile, operations/ftdc_test.go, operations/hello_test.go, repobuilder/config_test.go, repobuilder/deb_test.go, repobuilder/rpm_test.go
JIRA: https://jira.mongodb.org/browse/EVG-12824
=> EVG-12824: update makefile and evergreen.yaml

cmd/run-linter/run-linter.go, makefile, operations/ftdc.go
JIRA: https://jira.mongodb.org/browse/EVG-12939
Also do some drive-by linting fixes.
=> EVG-12939: fix file closure in FTDC to JSON

evergreen.yaml
JIRA: https://jira.mongodb.org/browse/EVG-12954
=> EVG-12954: set GOOS to ensure that cross-compilation succeeds

repobuilder/job_test.go
JIRA: https://jira.mongodb.org/browse/EVG-9080
=> EVG-9080: use virtual hosted-style S3 URLs

LICENSE
JIRA: https://jira.mongodb.org/browse/EVG-14133
=> EVG-14133: add license

operations/sthree.go
JIRA: https://jira.mongodb.org/browse/EVG-14254
=> EVG-14254: fix s3 put output

glide.lock, vendor/github.com/evergreen-ci/poplar/.golangci.yml, vendor/github.com/evergreen-ci/poplar/cmd/run-linter/run-linter.go, vendor/github.com/evergreen-ci/poplar/evergreen.yaml, vendor/github.com/evergreen-ci/poplar/rpc/client.go, vendor/github.com/evergreen-ci/poplar/rpc/client_test.go, vendor/github.com/evergreen-ci/poplar/rpc/internal/collector.service.go, vendor/github.com/evergreen-ci/poplar/rpc/internal/collector.service_test.go
JIRA: https://jira.mongodb.org/browse/EVG-14199
=> EVG-14199: revendor poplar

repobuilder/job_test.go
JIRA: https://jira.mongodb.org/browse/EVG-14419
=> EVG-14419: update S3 object for TestProcessPackages

glide.lock, vendor/github.com/evergreen-ci/aviation/services/cedar.go, vendor/github.com/evergreen-ci/aviation/services/cedar_test.go, vendor/github.com/evergreen-ci/poplar/evergreen.yaml, vendor/github.com/evergreen-ci/poplar/glide.lock, vendor/github.com/evergreen-ci/poplar/makefile, vendor/github.com/evergreen-ci/timber/glide.lock
JIRA: https://jira.mongodb.org/browse/EVG-13974
=> EVG-13974: revendor aviation, poplar, and timber

operations/repo.go, operations/repo_test.go, repobuilder/job.go
JIRA: https://jira.mongodb.org/browse/EVG-15010
- Added checksum for package files that already exist in local staging.
- Added new options for the `curator repo submit` command to enable specification of different env var names for the notary token and notary key name.
- Cleaned up repo cli command code.
=> EVG-15010: Add checksum to repobuilder for local files

repobuilder/job.go
JIRA: https://jira.mongodb.org/browse/EVG-15010
=> EVG-15010: remove outdated file before linking in repobuilder job

go.mod, go.sum
JIRA: https://jira.mongodb.org/browse/EVG-15932
=> EVG-15932: Update poplar version

.golangci.yml, greenbay/check/base_test.go, greenbay/check/command_test.go, greenbay/check/compile_gcc.go, greenbay/check/compile_golang.go, greenbay/check/compile_windows.go, greenbay/check/init.go, greenbay/check/limit_unix.go, greenbay/check/limit_unix_test.go, greenbay/check/limit_windows.go, greenbay/config_parsing_test.go, greenbay/logging_linux.go, greenbay/logging_other.go, greenbay/logging_unix.go, greenbay/logging_windows.go, operations/artifacts.go
Jira: https://jira.mongodb.org/browse/EVG-15952
=> EVG-15952: use gofmt linter

go.mod, go.sum
JIRA: https://jira.mongodb.org/browse/EVG-15720
=> EVG-15720: upgrade timber and jasper

go.mod, go.sum, operations/buildlogger.go
[EVG-16236](https://jira.mongodb.org/browse/EVG-16236)
Accommodate changes from https://github.com/mongodb/grip/commit/898ba2888109b89e382fe10b1aed1574fe9fe484
=> EVG-16236 use new grip function signature

barquesubmit/client.go
Right now failure to parse the response body from a login request gives an error message without much useful context because the body isn't included. This commit fixes that by logging the body as well.
=> EVG-18311: add more logging to json parse failure
